
return {
	name = "M4A1",

	fireMode = "Continuous",
	projectileName = "Flame",
	muzzleAttachmentName = "Muzzle",
	muzzleFallbackOffset = CFrame.new(0, -1.5, 0),

	fireAnim = "rbxassetid://105980333065574";
	emptyFireAnim = "rbxassetid://105980333065574";
	fireSound = game.ReplicatedStorage.Sounds.M4A1.Fire;
	
	equipAnim = "rbxassetid://99339998455578";
	equipSound = game.ReplicatedStorage.Sounds.M4A1.Fire;
	
	deEquipAnim = "rbxassetid://103035895010736";
	deEquipSound = game.ReplicatedStorage.Sounds.M4A1.Fire;
	
	reloadAnim = "rbxassetid://118391725443571";
	reloadSound = game.ReplicatedStorage.Sounds.M4A1.Fire;
	
	emptyReloadAnim = "rbxassetid://118391725443571";
	emptyReloadSound = game.ReplicatedStorage.Sounds.M4A1.Fire;
	
	inspectAnim = "rbxassetid://123346981295193";
	inspectSound = game.ReplicatedStorage.Sounds.M4A1.Fire;
	
	idleAnim = "rbxassetid://89992382176742";
	
	TPIdleAnim = "rbxassetid://78169256670262";
	TPFireAnim = "rbxassetid://130046935122176";
	TPReloadAnim = "rbxassetid://138714143669373";

	thirdPersonGrip = nil :: CFrame?,
}
